(defun lua-title ()
  "Inserts a nice lua commented header"
  (interactive)
  (beginning-of-line)
  (delete-trailing-whitespace)
  (setq startPos (point))
  (insert "-- ")
  (end-of-line)
  (insert " --")
  (setq endPos (point))
  (setq chars (- endPos startPos))
  (previous-line)
  (insert-char ?- chars)
  (next-line)
  (newline)
  (beginning-of-line)
  (insert-char ?- chars)
  )
